require 'pathname'

rn_macos_path = ''
ws_dir = Pathname.new(__dir__)
until File.exist?("#{ws_dir}/node_modules/react-native-macos/scripts/react_native_pods.rb") || ws_dir.expand_path.to_s == '/'
  ws_dir = ws_dir.parent
  rn_macos_path = "../#{rn_macos_path}"
end

require "#{ws_dir}/node_modules/react-native-macos/scripts/react_native_pods.rb"
rn_macos_path = "#{rn_macos_path}node_modules/react-native-macos"
# Pod::UI.puts "ws_dir: #{ws_dir}  rn_macos_path:#{rn_macos_path}".red
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

prepare_react_native_project!

target 'el_tester-macOS' do
  platform :macos, '14.0'
  use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => rn_macos_path,
    :hermes_enabled => false,
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # @property (nonatomic, strong, readonly) dispatch_queue_t methodQueue RCT_DEPRECATED;
    # Property with 'retain (or strong)' attribute must be of object type
    # strong -> assign
    # On iOS, dispatch_queue_t is an Objective-C object (so strong works)
    # On macOS, dispatch_queue_t is a C type (not an object), so strong is invalid and assign is correct
    # Fix dispatch_queue_t strong attribute error on macOS
    react_core_path = "#{installer.sandbox.root}/Headers/Public/React-Core/React/RCTBridgeModule.h"
    if File.exist?(react_core_path)
      content = File.read(react_core_path)
      content.gsub!('@property (nonatomic, strong, readonly) dispatch_queue_t methodQueue',
                    '@property (nonatomic, assign, readonly) dispatch_queue_t methodQueue')
      File.write(react_core_path, content)
    end

    # installer.pods_project.targets.each do |target|
    #   target.build_configurations.each do |config|
    #     config.build_settings['CLANG_WARN_OBJC_ROOT_CLASS'] = 'NO'
    #   end
    # end
    react_native_post_install(installer, rn_macos_path)
  end
end
Pod::UI.puts "RCT_NEW_ARCH_ENABLED: #{ENV['RCT_NEW_ARCH_ENABLED'] == '1'}  ".red

